# global parameters
seed: 0                # random seed
gpu_nums: 1            # nums of gpu
batch_size: 64         # batch_size
sub_batch: 8           # each incoming network image
train_epoch: 164       # nums of epoch
batch_size_predict: 1         # predict_batch_size

# data augmentation
jitter: 0.2
exposure: 1.5
saturation: 1.5
hue: 0.1

# input size
W: 448        # width
H: 448        # height
C: 3          # channels

# optimizer
momentum: 0.9            # SGD momentum
decay: 0.0005            # weight decay
learning_rate: 0.0005    # learning rate
steps: [100, 200, 300, 10000, 15000]   # learning rate change strategy（step）
scales: [2.5, 2, 2, 0.1, 0.1]          # stride of learning_rate

# detection_layer
side: 7
num_Bbox: 3
classes: 20
noobject_scale: 0.5
object_scale: 1
class_scale: 1
coord_scale: 5

# predict thresh
pr_thresh: 0.005
iou_thresh: 0.5
filter_thresh: 0.2

# labels
VOC_NAMES:
  ['aeroplane', 'bicycle', 'bird', 'boat',
  'bottle', 'bus', 'car', 'cat', 'chair',
  'cow', 'diningtable', 'dog', 'horse',
  'motorbike', 'person', 'pottedplant',
  'sheep', 'sofa', 'train', 'tvmonitor']

# yolov1 backbone cfg
net_cfg:
#  '''CBL: [in_channels, out_channels, kernel_size]'''
#  '''maxpool: [k_size, stride]'''
#  '''one2three: [in_channels, out_channels, num_cycle]'''
#  '''local: [in_channels, out_channels, output_size, kernel_size, stride, padding, bias(boolean)]'''
#  '''dropout: [p, ]'''
#  '''linear: [in_features, out_features]'''
  [['CBL', [3, 64, 7, 2]], ['maxpool', [2, 2]],
   ['CBL', [64, 192, 3, 1]], ['maxpool', [2, 2]],
   ['CBL', [192, 128, 1, 1], [128, 256, 3, 1], [256, 256, 1, 1], [256, 512, 3, 1]],
   ['maxpool', [2, 2]],
   ['one2three', [512, 256, 4]],
   ['CBL', [512, 512, 1, 1], [512, 1024, 3, 1]], ['maxpool', [2, 2]],
   ['one2three', [1024, 512, 2]],
   ['CBL', [1024, 1024, 3, 1], [1024, 1024, 3, 2], [1024, 1024, 3, 1], [1024, 1024, 3, 1]],
   ['local', [1024, 256, 7, 3, 1, 1, True]], ['Flatten', ],
   ['dropout', [0.5, ]], ['linear', [12544, 1715]]]
